// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: airline.sql

package database

import (
	"context"
)

const countAirlines = `-- name: CountAirlines :one
SELECT
    COUNT(*) AS cont_airlines
FROM
    airlines
`

func (q *Queries) CountAirlines(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAirlines)
	var cont_airlines int64
	err := row.Scan(&cont_airlines)
	return cont_airlines, err
}

const createAirline = `-- name: CreateAirline :one
INSERT INTO
    airlines (
        flightsfrom_id,
        iata,
        name,
        is_active
    )
VALUES
    (?, ?, ?, ?)
RETURNING
    id, flightsfrom_id, iata, name, is_active
`

type CreateAirlineParams struct {
	FlightsfromID int64
	Iata          string
	Name          string
	IsActive      bool
}

func (q *Queries) CreateAirline(ctx context.Context, arg CreateAirlineParams) (Airline, error) {
	row := q.db.QueryRowContext(ctx, createAirline,
		arg.FlightsfromID,
		arg.Iata,
		arg.Name,
		arg.IsActive,
	)
	var i Airline
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.Iata,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const getAirline = `-- name: GetAirline :one
SELECT
    id, flightsfrom_id, iata, name, is_active
FROM
    airlines
WHERE
    airlines.id = ?
LIMIT
    1
`

func (q *Queries) GetAirline(ctx context.Context, id int64) (Airline, error) {
	row := q.db.QueryRowContext(ctx, getAirline, id)
	var i Airline
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.Iata,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const getAirlineByFlightsFromId = `-- name: GetAirlineByFlightsFromId :one
SELECT
    id, flightsfrom_id, iata, name, is_active
FROM
    airlines
WHERE
    airlines.flightsfrom_id = ?
LIMIT
    1
`

func (q *Queries) GetAirlineByFlightsFromId(ctx context.Context, flightsfromID int64) (Airline, error) {
	row := q.db.QueryRowContext(ctx, getAirlineByFlightsFromId, flightsfromID)
	var i Airline
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.Iata,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const getAirlines = `-- name: GetAirlines :many
SELECT
    id, flightsfrom_id, iata, name, is_active
FROM
    airlines
LIMIT
    ? OFFSET ?
`

type GetAirlinesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetAirlines(ctx context.Context, arg GetAirlinesParams) ([]Airline, error) {
	rows, err := q.db.QueryContext(ctx, getAirlines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Airline
	for rows.Next() {
		var i Airline
		if err := rows.Scan(
			&i.ID,
			&i.FlightsfromID,
			&i.Iata,
			&i.Name,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAirlines = `-- name: GetAllAirlines :many
SELECT
    id,
    name,
    iata
FROM
    airlines
`

type GetAllAirlinesRow struct {
	ID   int64
	Name string
	Iata string
}

func (q *Queries) GetAllAirlines(ctx context.Context) ([]GetAllAirlinesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAirlines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAirlinesRow
	for rows.Next() {
		var i GetAllAirlinesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Iata); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAirline = `-- name: UpdateAirline :one
UPDATE
    airlines
SET
    flightsfrom_id = ?,
    iata = ?,
    name = ?,
    is_active = ?
WHERE
    id = ?
RETURNING
    id, flightsfrom_id, iata, name, is_active
`

type UpdateAirlineParams struct {
	FlightsfromID int64
	Iata          string
	Name          string
	IsActive      bool
	ID            int64
}

func (q *Queries) UpdateAirline(ctx context.Context, arg UpdateAirlineParams) (Airline, error) {
	row := q.db.QueryRowContext(ctx, updateAirline,
		arg.FlightsfromID,
		arg.Iata,
		arg.Name,
		arg.IsActive,
		arg.ID,
	)
	var i Airline
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.Iata,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}
