// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: airline.sql

package database

import (
	"context"
)

const countAirlines = `-- name: CountAirlines :one
SELECT
    COUNT(*) AS count_airlines
FROM
    airlines
`

func (q *Queries) CountAirlines(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAirlines)
	var count_airlines int64
	err := row.Scan(&count_airlines)
	return count_airlines, err
}

const createAirline = `-- name: CreateAirline :one
INSERT INTO
    airlines (iata, name, is_lowcost)
VALUES
    (?, ?, ?)
RETURNING
    iata, name, is_lowcost
`

type CreateAirlineParams struct {
	Iata      string
	Name      string
	IsLowcost bool
}

func (q *Queries) CreateAirline(ctx context.Context, arg CreateAirlineParams) (Airline, error) {
	row := q.db.QueryRowContext(ctx, createAirline, arg.Iata, arg.Name, arg.IsLowcost)
	var i Airline
	err := row.Scan(&i.Iata, &i.Name, &i.IsLowcost)
	return i, err
}

const getAirline = `-- name: GetAirline :one
SELECT
    iata, name, is_lowcost
FROM
    airlines
WHERE
    iata = ?
LIMIT
    1
`

func (q *Queries) GetAirline(ctx context.Context, iata string) (Airline, error) {
	row := q.db.QueryRowContext(ctx, getAirline, iata)
	var i Airline
	err := row.Scan(&i.Iata, &i.Name, &i.IsLowcost)
	return i, err
}

const getAirlines = `-- name: GetAirlines :many
SELECT
    iata, name, is_lowcost
FROM
    airlines
ORDER BY
    name
LIMIT
    ? OFFSET ?
`

type GetAirlinesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetAirlines(ctx context.Context, arg GetAirlinesParams) ([]Airline, error) {
	rows, err := q.db.QueryContext(ctx, getAirlines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Airline
	for rows.Next() {
		var i Airline
		if err := rows.Scan(&i.Iata, &i.Name, &i.IsLowcost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAirlines = `-- name: GetAllAirlines :many
SELECT
    iata,
    name
FROM
    airlines
`

type GetAllAirlinesRow struct {
	Iata string
	Name string
}

func (q *Queries) GetAllAirlines(ctx context.Context) ([]GetAllAirlinesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAirlines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAirlinesRow
	for rows.Next() {
		var i GetAllAirlinesRow
		if err := rows.Scan(&i.Iata, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAirline = `-- name: UpdateAirline :one
UPDATE
    airlines
SET
    name = ?,
    is_lowcost = ?
WHERE
    iata = ?
RETURNING
    iata, name, is_lowcost
`

type UpdateAirlineParams struct {
	Name      string
	IsLowcost bool
	Iata      string
}

func (q *Queries) UpdateAirline(ctx context.Context, arg UpdateAirlineParams) (Airline, error) {
	row := q.db.QueryRowContext(ctx, updateAirline, arg.Name, arg.IsLowcost, arg.Iata)
	var i Airline
	err := row.Scan(&i.Iata, &i.Name, &i.IsLowcost)
	return i, err
}
