// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: airline.sql

package database

import (
	"context"
)

const createAirline = `-- name: CreateAirline :one
INSERT INTO
    airlines (
        iata,
        name,
        is_active
    )
VALUES
    (?, ?, ?)
RETURNING
    id, flightsfrom_id, iata, name, is_active
`

type CreateAirlineParams struct {
	Iata     string
	Name     string
	IsActive bool
}

func (q *Queries) CreateAirline(ctx context.Context, arg CreateAirlineParams) (Airline, error) {
	row := q.db.QueryRowContext(ctx, createAirline, arg.Iata, arg.Name, arg.IsActive)
	var i Airline
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.Iata,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const getAirline = `-- name: GetAirline :one
SELECT
    id, flightsfrom_id, iata, name, is_active
FROM
    airlines
WHERE
    airlines.id = ?
LIMIT
    1
`

func (q *Queries) GetAirline(ctx context.Context, id int64) (Airline, error) {
	row := q.db.QueryRowContext(ctx, getAirline, id)
	var i Airline
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.Iata,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const getAirlineByFlightsFromId = `-- name: GetAirlineByFlightsFromId :one
SELECT
    id, flightsfrom_id, iata, name, is_active
FROM
    airlines
WHERE
    airlines.flightsfrom_id = ?
LIMIT
    1
`

func (q *Queries) GetAirlineByFlightsFromId(ctx context.Context, flightsfromID int64) (Airline, error) {
	row := q.db.QueryRowContext(ctx, getAirlineByFlightsFromId, flightsfromID)
	var i Airline
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.Iata,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}
