// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: airport.sql

package database

import (
	"context"
)

const createAirport = `-- name: CreateAirport :one
INSERT INTO
    airports (iata, name, city_id)
VALUES
    (?, ?, ?)
RETURNING
    id, iata, name, city_id
`

type CreateAirportParams struct {
	Iata   string
	Name   string
	CityID int64
}

func (q *Queries) CreateAirport(ctx context.Context, arg CreateAirportParams) (Airport, error) {
	row := q.db.QueryRowContext(ctx, createAirport, arg.Iata, arg.Name, arg.CityID)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.Iata,
		&i.Name,
		&i.CityID,
	)
	return i, err
}

const getAirportByIata = `-- name: GetAirportByIata :one
SELECT
    id, iata, name, city_id
FROM
    airports
WHERE
    airports.iata = ?
LIMIT
    1
`

func (q *Queries) GetAirportByIata(ctx context.Context, iata string) (Airport, error) {
	row := q.db.QueryRowContext(ctx, getAirportByIata, iata)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.Iata,
		&i.Name,
		&i.CityID,
	)
	return i, err
}
