// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: airport.sql

package database

import (
	"context"
)

const countAirports = `-- name: CountAirports :one
SELECT
    COUNT(*) AS count_airports
FROM
    airports
`

func (q *Queries) CountAirports(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAirports)
	var count_airports int64
	err := row.Scan(&count_airports)
	return count_airports, err
}

const createAirport = `-- name: CreateAirport :one
INSERT INTO
    airports (iata, name, iata_type, flightable, city_iata)
VALUES
    (?, ?, ?, ?, ?)
RETURNING
    iata, name, iata_type, flightable, city_iata
`

type CreateAirportParams struct {
	Iata       string
	Name       string
	IataType   string
	Flightable bool
	CityIata   string
}

func (q *Queries) CreateAirport(ctx context.Context, arg CreateAirportParams) (Airport, error) {
	row := q.db.QueryRowContext(ctx, createAirport,
		arg.Iata,
		arg.Name,
		arg.IataType,
		arg.Flightable,
		arg.CityIata,
	)
	var i Airport
	err := row.Scan(
		&i.Iata,
		&i.Name,
		&i.IataType,
		&i.Flightable,
		&i.CityIata,
	)
	return i, err
}

const getAirport = `-- name: GetAirport :one
SELECT
    a.iata,
    a.name,
    a.iata_type,
    a.flightable,
    a.city_iata,
    c.name AS city_name
FROM
    airports a
    JOIN cities c ON a.city_iata = c.iata
WHERE
    a.iata = ?
LIMIT
    1
`

type GetAirportRow struct {
	Iata       string
	Name       string
	IataType   string
	Flightable bool
	CityIata   string
	CityName   string
}

func (q *Queries) GetAirport(ctx context.Context, iata string) (GetAirportRow, error) {
	row := q.db.QueryRowContext(ctx, getAirport, iata)
	var i GetAirportRow
	err := row.Scan(
		&i.Iata,
		&i.Name,
		&i.IataType,
		&i.Flightable,
		&i.CityIata,
		&i.CityName,
	)
	return i, err
}

const getAirports = `-- name: GetAirports :many
SELECT
    a.iata,
    a.name,
    a.iata_type,
    a.flightable,
    a.city_iata,
    c.name AS city_name
FROM
    airports a
    JOIN cities c ON a.city_iata = c.iata
LIMIT
    ? OFFSET ?
`

type GetAirportsParams struct {
	Limit  int64
	Offset int64
}

type GetAirportsRow struct {
	Iata       string
	Name       string
	IataType   string
	Flightable bool
	CityIata   string
	CityName   string
}

func (q *Queries) GetAirports(ctx context.Context, arg GetAirportsParams) ([]GetAirportsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAirports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAirportsRow
	for rows.Next() {
		var i GetAirportsRow
		if err := rows.Scan(
			&i.Iata,
			&i.Name,
			&i.IataType,
			&i.Flightable,
			&i.CityIata,
			&i.CityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAirports = `-- name: GetAllAirports :many
SELECT
    a.iata,
    c.name AS city_name
FROM
    airports a
    JOIN cities c ON a.city_iata = c.iata
`

type GetAllAirportsRow struct {
	Iata     string
	CityName string
}

func (q *Queries) GetAllAirports(ctx context.Context) ([]GetAllAirportsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAirports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAirportsRow
	for rows.Next() {
		var i GetAllAirportsRow
		if err := rows.Scan(&i.Iata, &i.CityName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAirport = `-- name: UpdateAirport :one
UPDATE
    airports
SET
    name = ?,
    iata_type = ?,
    flightable = ?,
    city_iata = ?
WHERE
    iata = ?
RETURNING
    iata, name, iata_type, flightable, city_iata
`

type UpdateAirportParams struct {
	Name       string
	IataType   string
	Flightable bool
	CityIata   string
	Iata       string
}

func (q *Queries) UpdateAirport(ctx context.Context, arg UpdateAirportParams) (Airport, error) {
	row := q.db.QueryRowContext(ctx, updateAirport,
		arg.Name,
		arg.IataType,
		arg.Flightable,
		arg.CityIata,
		arg.Iata,
	)
	var i Airport
	err := row.Scan(
		&i.Iata,
		&i.Name,
		&i.IataType,
		&i.Flightable,
		&i.CityIata,
	)
	return i, err
}
