// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: airport.sql

package database

import (
	"context"
)

const countAirports = `-- name: CountAirports :one
SELECT
    COUNT(*) AS count_airports
FROM
    airports
`

func (q *Queries) CountAirports(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAirports)
	var count_airports int64
	err := row.Scan(&count_airports)
	return count_airports, err
}

const createAirport = `-- name: CreateAirport :one
INSERT INTO
    airports (iata, name, city_id)
VALUES
    (?, ?, ?)
RETURNING
    id, iata, name, city_id
`

type CreateAirportParams struct {
	Iata   string
	Name   string
	CityID int64
}

func (q *Queries) CreateAirport(ctx context.Context, arg CreateAirportParams) (Airport, error) {
	row := q.db.QueryRowContext(ctx, createAirport, arg.Iata, arg.Name, arg.CityID)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.Iata,
		&i.Name,
		&i.CityID,
	)
	return i, err
}

const getAirportByIata = `-- name: GetAirportByIata :one
SELECT
    id, iata, name, city_id
FROM
    airports
WHERE
    airports.iata = ?
LIMIT
    1
`

func (q *Queries) GetAirportByIata(ctx context.Context, iata string) (Airport, error) {
	row := q.db.QueryRowContext(ctx, getAirportByIata, iata)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.Iata,
		&i.Name,
		&i.CityID,
	)
	return i, err
}

const getAirports = `-- name: GetAirports :many
SELECT
    a.id,
    a.iata,
    a.name,
    a.city_id,
    c.name city_name
FROM
    airports a
    JOIN cities c ON a.city_id = c.id
LIMIT
    ? OFFSET ?
`

type GetAirportsParams struct {
	Limit  int64
	Offset int64
}

type GetAirportsRow struct {
	ID       int64
	Iata     string
	Name     string
	CityID   int64
	CityName string
}

func (q *Queries) GetAirports(ctx context.Context, arg GetAirportsParams) ([]GetAirportsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAirports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAirportsRow
	for rows.Next() {
		var i GetAirportsRow
		if err := rows.Scan(
			&i.ID,
			&i.Iata,
			&i.Name,
			&i.CityID,
			&i.CityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
