// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city.sql

package database

import (
	"context"
)

const createCity = `-- name: CreateCity :one
INSERT INTO
    cities (name, country_id)
VALUES
    (?, ?)
RETURNING
    id, name, country_id
`

type CreateCityParams struct {
	Name      string
	CountryID int64
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, createCity, arg.Name, arg.CountryID)
	var i City
	err := row.Scan(&i.ID, &i.Name, &i.CountryID)
	return i, err
}

const getCityByCountyCodeAndName = `-- name: GetCityByCountyCodeAndName :one
SELECT
    cities.id, cities.name, cities.country_id
FROM
    cities
    JOIN countries ON cities.country_id = countries.id
WHERE
    cities.name = ?
    AND countries.country_code = ?
LIMIT
    1
`

type GetCityByCountyCodeAndNameParams struct {
	Name        string
	CountryCode string
}

func (q *Queries) GetCityByCountyCodeAndName(ctx context.Context, arg GetCityByCountyCodeAndNameParams) (City, error) {
	row := q.db.QueryRowContext(ctx, getCityByCountyCodeAndName, arg.Name, arg.CountryCode)
	var i City
	err := row.Scan(&i.ID, &i.Name, &i.CountryID)
	return i, err
}
