// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city.sql

package database

import (
	"context"
)

const countCities = `-- name: CountCities :one
SELECT
    COUNT(*) AS count_cities
FROM
    cities
`

func (q *Queries) CountCities(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCities)
	var count_cities int64
	err := row.Scan(&count_cities)
	return count_cities, err
}

const createCity = `-- name: CreateCity :one
INSERT INTO
    cities (iata, name, country_code)
VALUES
    (?, ?, ?)
RETURNING
    iata, name, country_code
`

type CreateCityParams struct {
	Iata        string
	Name        string
	CountryCode string
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, createCity, arg.Iata, arg.Name, arg.CountryCode)
	var i City
	err := row.Scan(&i.Iata, &i.Name, &i.CountryCode)
	return i, err
}

const getAllCities = `-- name: GetAllCities :many
SELECT
    ct.iata,
    cr.name || ' - ' || ct.name name
FROM
    cities ct
    JOIN countries cr ON ct.country_code = cr.code
`

type GetAllCitiesRow struct {
	Iata string
	Name interface{}
}

func (q *Queries) GetAllCities(ctx context.Context) ([]GetAllCitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCitiesRow
	for rows.Next() {
		var i GetAllCitiesRow
		if err := rows.Scan(&i.Iata, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCities = `-- name: GetCities :many
SELECT
    ct.iata,
    ct.name,
    ct.country_code,
    cr.name AS country_name
FROM
    cities ct
    JOIN countries cr ON ct.country_code = cr.code
LIMIT
    ? OFFSET ?
`

type GetCitiesParams struct {
	Limit  int64
	Offset int64
}

type GetCitiesRow struct {
	Iata        string
	Name        string
	CountryCode string
	CountryName string
}

func (q *Queries) GetCities(ctx context.Context, arg GetCitiesParams) ([]GetCitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCitiesRow
	for rows.Next() {
		var i GetCitiesRow
		if err := rows.Scan(
			&i.Iata,
			&i.Name,
			&i.CountryCode,
			&i.CountryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCity = `-- name: GetCity :one
SELECT
    ct.iata,
    ct.name,
    ct.country_code,
    cr.name AS country_name
FROM
    cities ct
    JOIN countries cr ON ct.country_code = cr.code
WHERE
    ct.iata = ?
LIMIT
    1
`

type GetCityRow struct {
	Iata        string
	Name        string
	CountryCode string
	CountryName string
}

func (q *Queries) GetCity(ctx context.Context, iata string) (GetCityRow, error) {
	row := q.db.QueryRowContext(ctx, getCity, iata)
	var i GetCityRow
	err := row.Scan(
		&i.Iata,
		&i.Name,
		&i.CountryCode,
		&i.CountryName,
	)
	return i, err
}

const updateCity = `-- name: UpdateCity :one
UPDATE
    cities
SET
    name = ?,
    country_code = ?
WHERE
    iata = ?
RETURNING
    iata, name, country_code
`

type UpdateCityParams struct {
	Name        string
	CountryCode string
	Iata        string
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, updateCity, arg.Name, arg.CountryCode, arg.Iata)
	var i City
	err := row.Scan(&i.Iata, &i.Name, &i.CountryCode)
	return i, err
}
