// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city.sql

package database

import (
	"context"
)

const countCities = `-- name: CountCities :one
SELECT
    COUNT(*) AS count_cities
FROM
    cities
`

func (q *Queries) CountCities(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCities)
	var count_cities int64
	err := row.Scan(&count_cities)
	return count_cities, err
}

const createCity = `-- name: CreateCity :one
INSERT INTO
    cities (name, country_id)
VALUES
    (?, ?)
RETURNING
    id, name, country_id
`

type CreateCityParams struct {
	Name      string
	CountryID int64
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, createCity, arg.Name, arg.CountryID)
	var i City
	err := row.Scan(&i.ID, &i.Name, &i.CountryID)
	return i, err
}

const getCities = `-- name: GetCities :many
SELECT
    ct.id,
    ct.name,
    ct.country_id,
    cr.name AS country_name,
    cr.country_code
FROM
    cities ct
    JOIN countries cr ON ct.country_id = cr.id
LIMIT
    ? OFFSET ?
`

type GetCitiesParams struct {
	Limit  int64
	Offset int64
}

type GetCitiesRow struct {
	ID          int64
	Name        string
	CountryID   int64
	CountryName string
	CountryCode string
}

func (q *Queries) GetCities(ctx context.Context, arg GetCitiesParams) ([]GetCitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCitiesRow
	for rows.Next() {
		var i GetCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CountryID,
			&i.CountryName,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCity = `-- name: GetCity :one
SELECT
    ct.id,
    ct.name,
    ct.country_id,
    cr.name AS country_name,
    cr.country_code
FROM
    cities ct
    JOIN countries cr ON ct.country_id = cr.id
WHERE
    ct.id = ?
LIMIT
    1
`

type GetCityRow struct {
	ID          int64
	Name        string
	CountryID   int64
	CountryName string
	CountryCode string
}

func (q *Queries) GetCity(ctx context.Context, id int64) (GetCityRow, error) {
	row := q.db.QueryRowContext(ctx, getCity, id)
	var i GetCityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CountryID,
		&i.CountryName,
		&i.CountryCode,
	)
	return i, err
}

const getCityByCountyCodeAndName = `-- name: GetCityByCountyCodeAndName :one
SELECT
    cities.id, cities.name, cities.country_id
FROM
    cities
    JOIN countries ON cities.country_id = countries.id
WHERE
    cities.name = ?
    AND countries.country_code = ?
LIMIT
    1
`

type GetCityByCountyCodeAndNameParams struct {
	Name        string
	CountryCode string
}

func (q *Queries) GetCityByCountyCodeAndName(ctx context.Context, arg GetCityByCountyCodeAndNameParams) (City, error) {
	row := q.db.QueryRowContext(ctx, getCityByCountyCodeAndName, arg.Name, arg.CountryCode)
	var i City
	err := row.Scan(&i.ID, &i.Name, &i.CountryID)
	return i, err
}
