// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: country.sql

package database

import (
	"context"
)

const countCountries = `-- name: CountCountries :one
SELECT
    COUNT(*) AS count_countries
FROM
    countries
`

func (q *Queries) CountCountries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCountries)
	var count_countries int64
	err := row.Scan(&count_countries)
	return count_countries, err
}

const createCountry = `-- name: CreateCountry :one
INSERT INTO
    countries (country_code, name)
VALUES
    (?, ?)
RETURNING
    id, country_code, name
`

type CreateCountryParams struct {
	CountryCode string
	Name        string
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, createCountry, arg.CountryCode, arg.Name)
	var i Country
	err := row.Scan(&i.ID, &i.CountryCode, &i.Name)
	return i, err
}

const getCountries = `-- name: GetCountries :many
SELECT
    id, country_code, name
FROM
    countries
LIMIT
    ? OFFSET ?
`

type GetCountriesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetCountries(ctx context.Context, arg GetCountriesParams) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, getCountries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(&i.ID, &i.CountryCode, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountry = `-- name: GetCountry :one
SELECT
    id, country_code, name
FROM
    countries
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetCountry(ctx context.Context, id int64) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountry, id)
	var i Country
	err := row.Scan(&i.ID, &i.CountryCode, &i.Name)
	return i, err
}

const getCountryByCode = `-- name: GetCountryByCode :one
SELECT
    id, country_code, name
FROM
    countries
WHERE
    country_code = ?
LIMIT
    1
`

func (q *Queries) GetCountryByCode(ctx context.Context, countryCode string) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountryByCode, countryCode)
	var i Country
	err := row.Scan(&i.ID, &i.CountryCode, &i.Name)
	return i, err
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE
    countries
SET
    country_code = ?,
    name = ?
WHERE
    id = ?
RETURNING
    id, country_code, name
`

type UpdateCountryParams struct {
	CountryCode string
	Name        string
	ID          int64
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, updateCountry, arg.CountryCode, arg.Name, arg.ID)
	var i Country
	err := row.Scan(&i.ID, &i.CountryCode, &i.Name)
	return i, err
}
