// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: country.sql

package database

import (
	"context"
)

const countCountries = `-- name: CountCountries :one
SELECT
    COUNT(*) AS count_countries
FROM
    countries
`

func (q *Queries) CountCountries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCountries)
	var count_countries int64
	err := row.Scan(&count_countries)
	return count_countries, err
}

const createCountry = `-- name: CreateCountry :one
INSERT INTO
    countries (code, name)
VALUES
    (?, ?)
RETURNING
    code, name
`

type CreateCountryParams struct {
	Code string
	Name string
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, createCountry, arg.Code, arg.Name)
	var i Country
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const getAllCountries = `-- name: GetAllCountries :many
SELECT
    name,
    code
FROM
    countries
`

type GetAllCountriesRow struct {
	Name string
	Code string
}

func (q *Queries) GetAllCountries(ctx context.Context) ([]GetAllCountriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCountriesRow
	for rows.Next() {
		var i GetAllCountriesRow
		if err := rows.Scan(&i.Name, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountries = `-- name: GetCountries :many
SELECT
    code, name
FROM
    countries
LIMIT
    ? OFFSET ?
`

type GetCountriesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetCountries(ctx context.Context, arg GetCountriesParams) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, getCountries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountry = `-- name: GetCountry :one
SELECT
    code, name
FROM
    countries
WHERE
    code = ?
LIMIT
    1
`

func (q *Queries) GetCountry(ctx context.Context, code string) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountry, code)
	var i Country
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE
    countries
SET
    name = ?
WHERE
    code = ?
RETURNING
    code, name
`

type UpdateCountryParams struct {
	Name string
	Code string
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, updateCountry, arg.Name, arg.Code)
	var i Country
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}
