// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: country.sql

package database

import (
	"context"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO
    countries (country_code, name)
VALUES
    (?, ?)
RETURNING
    id, country_code, name
`

type CreateCountryParams struct {
	CountryCode string
	Name        string
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, createCountry, arg.CountryCode, arg.Name)
	var i Country
	err := row.Scan(&i.ID, &i.CountryCode, &i.Name)
	return i, err
}

const getCountryByCode = `-- name: GetCountryByCode :one
SELECT
    id, country_code, name
FROM
    countries
WHERE
    country_code = ?
LIMIT
    1
`

func (q *Queries) GetCountryByCode(ctx context.Context, countryCode string) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountryByCode, countryCode)
	var i Country
	err := row.Scan(&i.ID, &i.CountryCode, &i.Name)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id, country_code, name
FROM
    countries
`

func (q *Queries) ListUsers(ctx context.Context) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(&i.ID, &i.CountryCode, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
