// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Airline struct {
	ID            int64
	FlightsfromID int64
	Iata          string
	Name          string
	IsActive      bool
}

type Airport struct {
	ID     int64
	Iata   string
	Name   string
	CityID int64
}

type City struct {
	ID        int64
	Name      string
	CountryID int64
}

type Country struct {
	ID          int64
	CountryCode string
	Name        string
}

type Route struct {
	ID            int64
	FlightsfromID int64
	AirlineID     int64
	AirportFromID int64
	AirportToID   int64
	IsActive      bool
}
