// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Airline struct {
	Iata      string
	Name      string
	IsLowcost bool
}

type Airport struct {
	Iata       string
	Name       string
	IataType   string
	Flightable bool
	CityIata   string
}

type City struct {
	Iata        string
	Name        string
	CountryCode string
}

type Country struct {
	Code string
	Name string
}

type PriceSnapshot struct {
	ID              int64
	FlightNumber    string
	OriginIata      string
	DestinationIata string
	DepartureAt     string
	AirlineIata     string
	Price           interface{}
	ObservedAt      string
}

type WatchedRoute struct {
	OriginIata      string
	DestinationIata string
	Active          bool
}
