// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Airline struct {
	ID        int64
	Callsign  string
	Icao      string
	Iata      string
	Name      string
	ShortName string
	FullName  string
	IsActive  bool
	CountryID sql.NullInt64
}

type Airport struct {
	Iata   string
	Name   string
	CityID int64
}

type City struct {
	ID        int64
	Name      string
	CountryID interface{}
}

type Country struct {
	ID          int64
	CountryCode string
	Name        string
}

type Route struct {
	ID            int64
	AirlineID     int64
	AirportFromID int64
	AirportToID   int64
	IsActive      bool
	Day1          bool
	Day2          bool
	Day3          bool
	Day4          bool
	Day5          bool
	Day6          bool
	Day7          bool
}
