// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_snapshot.sql

package database

import (
	"context"
)

const createPriceSnapshot = `-- name: CreatePriceSnapshot :exec
INSERT
    OR IGNORE INTO price_snapshots(
        flight_number,
        origin_iata,
        destination_iata,
        departure_at,
        airline_iata,
        price,
        observed_at
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type CreatePriceSnapshotParams struct {
	FlightNumber    string
	OriginIata      string
	DestinationIata string
	DepartureAt     string
	AirlineIata     string
	Price           interface{}
	ObservedAt      string
}

func (q *Queries) CreatePriceSnapshot(ctx context.Context, arg CreatePriceSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createPriceSnapshot,
		arg.FlightNumber,
		arg.OriginIata,
		arg.DestinationIata,
		arg.DepartureAt,
		arg.AirlineIata,
		arg.Price,
		arg.ObservedAt,
	)
	return err
}
