// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route.sql

package database

import (
	"context"
)

const countRoutes = `-- name: CountRoutes :one
SELECT
    COUNT(*) AS count_routes
FROM
    routes
`

func (q *Queries) CountRoutes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoutes)
	var count_routes int64
	err := row.Scan(&count_routes)
	return count_routes, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO
    routes (
        flightsfrom_id,
        airline_id,
        airport_from_id,
        airport_to_id,
        is_active
    )
VALUES
    (?, ?, ?, ?, ?)
RETURNING
    id, flightsfrom_id, airline_id, airport_from_id, airport_to_id, is_active
`

type CreateRouteParams struct {
	FlightsfromID int64
	AirlineID     int64
	AirportFromID int64
	AirportToID   int64
	IsActive      bool
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, createRoute,
		arg.FlightsfromID,
		arg.AirlineID,
		arg.AirportFromID,
		arg.AirportToID,
		arg.IsActive,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.AirlineID,
		&i.AirportFromID,
		&i.AirportToID,
		&i.IsActive,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT
    r.id,
    r.flightsfrom_id,
    r.is_active,
    r.airline_id,
    ar.name AS airline_name,
    ar.iata AS airline_iata,
    r.airport_from_id,
    af.iata AS airport_from_iata,
    cf.name AS city_from_name,
    r.airport_to_id,
    at.iata AS airport_to_iata,
    ct.name AS city_to_name
FROM
    routes r
    JOIN airlines ar ON ar.id = r.airline_id
    JOIN airports af ON af.id = r.airport_from_id
    JOIN airports at ON at.id = r.airport_to_id
    JOIN cities cf ON cf.id = af.city_id
    JOIN cities ct ON ct.id = at.city_id
WHERE
    r.id = ?
LIMIT
    1
`

type GetRouteRow struct {
	ID              int64
	FlightsfromID   int64
	IsActive        bool
	AirlineID       int64
	AirlineName     string
	AirlineIata     string
	AirportFromID   int64
	AirportFromIata string
	CityFromName    string
	AirportToID     int64
	AirportToIata   string
	CityToName      string
}

func (q *Queries) GetRoute(ctx context.Context, id int64) (GetRouteRow, error) {
	row := q.db.QueryRowContext(ctx, getRoute, id)
	var i GetRouteRow
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.IsActive,
		&i.AirlineID,
		&i.AirlineName,
		&i.AirlineIata,
		&i.AirportFromID,
		&i.AirportFromIata,
		&i.CityFromName,
		&i.AirportToID,
		&i.AirportToIata,
		&i.CityToName,
	)
	return i, err
}

const getRouteByFlightsFromId = `-- name: GetRouteByFlightsFromId :one
SELECT
    id, flightsfrom_id, airline_id, airport_from_id, airport_to_id, is_active
FROM
    routes
WHERE
    routes.flightsfrom_id = ?
LIMIT
    1
`

func (q *Queries) GetRouteByFlightsFromId(ctx context.Context, flightsfromID int64) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByFlightsFromId, flightsfromID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.AirlineID,
		&i.AirportFromID,
		&i.AirportToID,
		&i.IsActive,
	)
	return i, err
}

const getRoutes = `-- name: GetRoutes :many
SELECT
    r.id,
    r.airport_from_id,
    cf.name AS city_from_name,
    af.iata AS airport_from_iata,
    r.airport_to_id,
    ct.name AS city_to_name,
    at.iata AS airport_to_iata,
    r.airline_id,
    ar.name AS airline_name
FROM
    routes r
    JOIN airports af ON af.id = r.airport_from_id
    JOIN airports at ON at.id = r.airport_to_id
    JOIN airlines ar ON ar.id = r.airline_id
    JOIN cities cf ON af.city_id = cf.id
    JOIN cities ct ON at.city_id = ct.id
LIMIT
    ? OFFSET ?
`

type GetRoutesParams struct {
	Limit  int64
	Offset int64
}

type GetRoutesRow struct {
	ID              int64
	AirportFromID   int64
	CityFromName    string
	AirportFromIata string
	AirportToID     int64
	CityToName      string
	AirportToIata   string
	AirlineID       int64
	AirlineName     string
}

func (q *Queries) GetRoutes(ctx context.Context, arg GetRoutesParams) ([]GetRoutesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoutes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoutesRow
	for rows.Next() {
		var i GetRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.AirportFromID,
			&i.CityFromName,
			&i.AirportFromIata,
			&i.AirportToID,
			&i.CityToName,
			&i.AirportToIata,
			&i.AirlineID,
			&i.AirlineName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE
    routes
SET
    flightsfrom_id = ?,
    airline_id = ?,
    airport_from_id = ?,
    airport_to_id = ?,
    is_active = ?
WHERE
    id = ?
RETURNING
    id, flightsfrom_id, airline_id, airport_from_id, airport_to_id, is_active
`

type UpdateRouteParams struct {
	FlightsfromID int64
	AirlineID     int64
	AirportFromID int64
	AirportToID   int64
	IsActive      bool
	ID            int64
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, updateRoute,
		arg.FlightsfromID,
		arg.AirlineID,
		arg.AirportFromID,
		arg.AirportToID,
		arg.IsActive,
		arg.ID,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.AirlineID,
		&i.AirportFromID,
		&i.AirportToID,
		&i.IsActive,
	)
	return i, err
}
