// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route.sql

package database

import (
	"context"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO
    routes (
        flightsfrom_id,
        airline_id,
        airport_from_id,
        airport_to_id,
        is_active
    )
VALUES
    (?, ?, ?, ?, ?)
RETURNING
    id, flightsfrom_id, airline_id, airport_from_id, airport_to_id, is_active
`

type CreateRouteParams struct {
	FlightsfromID int64
	AirlineID     int64
	AirportFromID int64
	AirportToID   int64
	IsActive      bool
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, createRoute,
		arg.FlightsfromID,
		arg.AirlineID,
		arg.AirportFromID,
		arg.AirportToID,
		arg.IsActive,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.AirlineID,
		&i.AirportFromID,
		&i.AirportToID,
		&i.IsActive,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT
    id, flightsfrom_id, airline_id, airport_from_id, airport_to_id, is_active
FROM
    routes
WHERE
    routes.id = ?
LIMIT
    1
`

func (q *Queries) GetRoute(ctx context.Context, id int64) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.AirlineID,
		&i.AirportFromID,
		&i.AirportToID,
		&i.IsActive,
	)
	return i, err
}

const getRouteByFlightsFromId = `-- name: GetRouteByFlightsFromId :one
SELECT
    id, flightsfrom_id, airline_id, airport_from_id, airport_to_id, is_active
FROM
    routes
WHERE
    routes.flightsfrom_id = ?
LIMIT
    1
`

func (q *Queries) GetRouteByFlightsFromId(ctx context.Context, flightsfromID int64) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByFlightsFromId, flightsfromID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.FlightsfromID,
		&i.AirlineID,
		&i.AirportFromID,
		&i.AirportToID,
		&i.IsActive,
	)
	return i, err
}
