// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stat.sql

package database

import (
	"context"
)

const getStats = `-- name: GetStats :one
SELECT
    (
        SELECT
            COUNT(*)
        FROM
            routes
    ) AS routes_num,
    (
        SELECT
            COUNT(*)
        FROM
            airlines
    ) AS airlines_num,
    (
        SELECT
            COUNT(*)
        FROM
            airports
    ) AS airports_num,
    (
        SELECT
            COUNT(*)
        FROM
            cities
    ) AS cities_num,
    (
        SELECT
            COUNT(*)
        FROM
            countries
    ) AS countries_num
`

type GetStatsRow struct {
	RoutesNum    int64
	AirlinesNum  int64
	AirportsNum  int64
	CitiesNum    int64
	CountriesNum int64
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.RoutesNum,
		&i.AirlinesNum,
		&i.AirportsNum,
		&i.CitiesNum,
		&i.CountriesNum,
	)
	return i, err
}
