// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watched_route.sql

package database

import (
	"context"
)

const changeActive = `-- name: ChangeActive :one
UPDATE
    watched_routes
SET
    active = ?
WHERE
    origin_iata = ?
    AND destination_iata = ?
RETURNING
    origin_iata, destination_iata, active
`

type ChangeActiveParams struct {
	Active          bool
	OriginIata      string
	DestinationIata string
}

func (q *Queries) ChangeActive(ctx context.Context, arg ChangeActiveParams) (WatchedRoute, error) {
	row := q.db.QueryRowContext(ctx, changeActive, arg.Active, arg.OriginIata, arg.DestinationIata)
	var i WatchedRoute
	err := row.Scan(&i.OriginIata, &i.DestinationIata, &i.Active)
	return i, err
}

const countWatchedRoutes = `-- name: CountWatchedRoutes :one
SELECT
    COUNT(*)
FROM
    watched_routes
`

func (q *Queries) CountWatchedRoutes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWatchedRoutes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWatchedRoute = `-- name: CreateWatchedRoute :one
INSERT INTO
    watched_routes(origin_iata, destination_iata, active)
VALUES
    (?, ?, ?)
RETURNING
    origin_iata, destination_iata, active
`

type CreateWatchedRouteParams struct {
	OriginIata      string
	DestinationIata string
	Active          bool
}

func (q *Queries) CreateWatchedRoute(ctx context.Context, arg CreateWatchedRouteParams) (WatchedRoute, error) {
	row := q.db.QueryRowContext(ctx, createWatchedRoute, arg.OriginIata, arg.DestinationIata, arg.Active)
	var i WatchedRoute
	err := row.Scan(&i.OriginIata, &i.DestinationIata, &i.Active)
	return i, err
}

const getWatchedRoutes = `-- name: GetWatchedRoutes :many
SELECT
    origin_iata, destination_iata, active
FROM
    watched_routes
LIMIT
    ? OFFSET ?
`

type GetWatchedRoutesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetWatchedRoutes(ctx context.Context, arg GetWatchedRoutesParams) ([]WatchedRoute, error) {
	rows, err := q.db.QueryContext(ctx, getWatchedRoutes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchedRoute
	for rows.Next() {
		var i WatchedRoute
		if err := rows.Scan(&i.OriginIata, &i.DestinationIata, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
